APPLY_FIXES: none
FORMATTERS_DISABLE_ERRORS: false
IGNORE_GENERATED_FILES: true
SHOW_ELAPSED_TIME: true
VALIDATE_ALL_CODEBASE: true

ENABLE_LINTERS:
  - ACTION_ACTIONLINT
  - CPP_CPPCHECK
  - JAVASCRIPT_ES
  - JSON_PRETTIER
  - MARKDOWN_MARKDOWNLINT
  - TSX_ESLINT
  - TYPESCRIPT_ES
  - YAML_PRETTIER
